"""
reward_program.py -- Generation 26
Auto-generated by RewardDesigner. DO NOT EDIT MANUALLY.
"""

def compute_reward(state):
    if state["collided"]:
        return -100.0
    speed = state["speed_ms"]
    open_road = state["front_dist"] > 45.0 and state["ttc"] > 6.0
    clear_road = state["front_dist"] > 55.0 and state["ttc"] > 6.0
    speed_reward = clip(speed * 0.08, 0.0, 3.0)
    slow_penalty = -10.0 if clear_road and speed < 24.0 else 0.0
    passive_band_tax = -12.0 if open_road and not state["overtook"] and speed > 20.0 and speed <= 24.0 else 0.0
    static_passive_tax = -10.0 if open_road and not state["overtook"] and not state["lane_changed"] else 0.0
    cruise_tax = -15.0 if open_road and not state["overtook"] and speed > 24.0 else 0.0
    no_overtake_tax = (
        -15.0
        if open_road and not state["overtook"] and not state["lane_changed"]
        else (-12.0 if open_road and not state["overtook"] else 0.0)
    )
    ttc_penalty = -50.0 if state["ttc"] < 1.0 else -30.0 if state["ttc"] < 3.0 else 0.0
    tailgate_penalty = -25.0 if state["front_dist"] < 28.0 and state["ttc"] < 4.5 else 0.0
    overtake_bonus = 12.0 if state["overtook"] else 0.0
    jerk_penalty = -5.0 * (abs(state["long_jerk"]) + abs(state["lat_jerk"]))
    accel_penalty = -4.0 * abs(state["accel_ms2"])
    gap_bonus = 0.0001 * clip(state["front_dist"] - 35.0, 0.0, 10.0) if speed >= 24.0 else 0.0
    lc_penalty = -5.0 if state["lane_changed"] and not state["overtook"] else 0.0
    return (
        speed_reward
        + slow_penalty
        + passive_band_tax
        + static_passive_tax
        + cruise_tax
        + no_overtake_tax
        + ttc_penalty
        + tailgate_penalty
        + overtake_bonus
        + jerk_penalty
        + accel_penalty
        + gap_bonus
        + lc_penalty
    )