"""
reward_program.py -- Generation 3
Auto-generated by RewardDesigner. DO NOT EDIT MANUALLY.
"""

def compute_reward(state):
    if state["collided"]:
        return -30.0
    speed = state["speed_ms"]
    clear_road = state["front_dist"] > 40.0 and state["ttc"] > 5.0
    speed_reward = clip(speed * 0.15, 0.0, 5.0)
    slow_penalty = -0.8 if clear_road and speed < 24.0 else 0.0
    cruise_tax = -2.5 if clear_road and not state["overtook"] and speed > 24.0 else 0.0
    no_overtake_tax = (
        -1.5
        if clear_road and not state["overtook"] and not state["lane_changed"]
        else (-0.6 if clear_road and not state["overtook"] else 0.0)
    )
    ttc_penalty = -4.0 if state["ttc"] < 1.0 else -2.0 if state["ttc"] < 3.0 else 0.0
    tailgate_penalty = -1.5 if state["front_dist"] < 20.0 and state["ttc"] < 4.0 else 0.0
    overtake_bonus = 4.0 if state["overtook"] else 0.0
    jerk_penalty = -0.10 * (abs(state["long_jerk"]) + abs(state["lat_jerk"]))
    accel_penalty = -0.06 * abs(state["accel_ms2"])
    gap_bonus = 0.010 * clip(state["front_dist"] - 25.0, 0.0, 15.0) if speed >= 24.0 else 0.0
    lc_penalty = -0.45 if state["lane_changed"] and not state["overtook"] else 0.0
    passive_driving_penalty = -0.2 if speed < 22.0 and state["front_dist"] > 40.0 and state["ttc"] > 5.0 else 0.0
    return (
        speed_reward
        + slow_penalty
        + cruise_tax
        + no_overtake_tax
        + ttc_penalty
        + tailgate_penalty
        + overtake_bonus
        + jerk_penalty
        + accel_penalty
        + gap_bonus
        + lc_penalty
        + passive_driving_penalty
    )