"""
reward_program.py -- Generation 0 (bootstrap default)
Auto-generated by RewardDesigner. DO NOT EDIT MANUALLY.

This is the seed reward program shipped with the repo so PPO training has
something to run before the LLM has produced any real generation. It will
be OVERWRITTEN the first time RewardDesigner.generate_reward() (--bootstrap)
or _evolve() succeeds -- at that point this hand-written version is archived
as the actual generation 0 in reward_archive.json, and the LLM takes over
from here.

Design notes (mirrors the same rules given to the LLM in
reward_designer.py's _GENERATION_SYSTEM prompt):
  * Hard safety check first: if state["collided"], return the collision
    penalty immediately with nothing else added.
  * Continuous, always-increasing speed term (capped, not unbounded).
  * TTC penalty only engages below 3s -- not punished during normal driving.
  * One-shot overtake bonus on state["overtook"] (NOTE: "overtook", not
    "overtake" -- see STATE SCHEMA in reward_designer.py).
  * Small jerk/accel penalties (0.02 scale) so they shape, not dominate.
  * Mild reward for keeping a safe following gap.
  * Small lane-change penalty so changes must be earned by the rest of the
    reward, not free.
"""

def compute_reward(state):
    if state["collided"]:
        return -30.0
    speed_reward = clip(state["speed_ms"] * 0.1, 0.0, 3.0)
    ttc_penalty = -3.0 if state["ttc"] < 1.0 else -1.0 if state["ttc"] < 3.0 else 0.0
    overtake_bonus = 2.0 if state["overtook"] else 0.0
    jerk_penalty = -0.02 * (abs(state["long_jerk"]) + abs(state["lat_jerk"]))
    accel_penalty = -0.02 * abs(state["accel_ms2"])
    safe_gap_reward = 0.05 * clip(state["front_dist"] - 15.0, 0.0, 30.0)
    lane_change_penalty = -0.1 if state["lane_changed"] else 0.0
    return (
        speed_reward
        + ttc_penalty
        + overtake_bonus
        + jerk_penalty
        + accel_penalty
        + safe_gap_reward
        + lane_change_penalty
    )
