"""Centralized runtime configuration.

Import hyperparameters and paths from submodules or re-exports here::

    from txt2reward.config import ENV_CONFIG, DEFAULT_EVOLVE_EVERY, LLM_MODEL

Submodules: ``paths``, ``training``, ``llm``, ``fitness``, ``validation``, ``env``.
"""

from txt2reward.config.env import ENV_CONFIG
from txt2reward.config.fitness import (
    ARCHIVE_FAILED_MAX_FITNESS,
    ARCHIVE_MIN_TOP_FITNESS,
    CRASH_FARMING_CRASH_MIN,
    CRASH_FARMING_SPEED_MIN,
    FITNESS_VERSION_DEFAULT,
)
from txt2reward.config.llm import (
    CRITIQUE_MAX_RETRIES,
    CRITIQUE_MAX_TOKENS,
    CRITIQUE_TEMPERATURE,
    GENERATION_MAX_RETRIES,
    GENERATION_MAX_TOKENS,
    GENERATION_TEMPERATURE,
    KEY_ROTATION_MAX_ROUNDS,
    KEY_ROTATION_WAIT_SEC,
    LLM_MODEL,
    LLM_PROVIDER,
)
from txt2reward.config.paths import (
    API_KEYS_FILE,
    ARCHIVE_FILE,
    LOG_FILE,
    REWARD_PROGRAM_PATH,
    WEIGHTS_FILE,
)
from txt2reward.config.training import (
    DEFAULT_CHECKPOINT_FREQ,
    DEFAULT_DRIVING_GOAL,
    DEFAULT_EVOLVE_EVERY,
    DEFAULT_N_ENVS,
    DEFAULT_PLOT_DIR,
    DEFAULT_PLOT_SMOOTH_WINDOW,
    DEFAULT_RELOAD_INTERVAL,
    DEFAULT_TOTAL_TIMESTEPS,
    DEFAULT_WARMUP_EPISODES,
    PPO_BATCH_SIZE,
    PPO_N_EPOCHS,
    PPO_N_STEPS,
    REWARD_STEP_CLIP_MAX,
    REWARD_STEP_CLIP_MIN,
)
from txt2reward.config.validation import (
    BANK_MAX_VIOLATION_RATE,
    BANK_MIN_FITNESS_GAP,
    REWARD_STEP_TIMEOUT_SEC,
    SANDBOX_EXECUTE_TIMEOUT_SEC,
    SMOKE_TEST_TIMEOUT_SEC,
    TRAJECTORY_BANK_MODE,
    TRAJECTORY_BANK_SEED,
    TRAJECTORY_REF_FITNESS_VERSION,
)

__all__ = [
    "ARCHIVE_FAILED_MAX_FITNESS",
    "ARCHIVE_FILE",
    "ARCHIVE_MIN_TOP_FITNESS",
    "BANK_MAX_VIOLATION_RATE",
    "BANK_MIN_FITNESS_GAP",
    "CRASH_FARMING_CRASH_MIN",
    "CRASH_FARMING_SPEED_MIN",
    "CRITIQUE_MAX_RETRIES",
    "CRITIQUE_MAX_TOKENS",
    "CRITIQUE_TEMPERATURE",
    "DEFAULT_CHECKPOINT_FREQ",
    "DEFAULT_DRIVING_GOAL",
    "DEFAULT_EVOLVE_EVERY",
    "DEFAULT_N_ENVS",
    "DEFAULT_PLOT_DIR",
    "DEFAULT_PLOT_SMOOTH_WINDOW",
    "DEFAULT_RELOAD_INTERVAL",
    "DEFAULT_TOTAL_TIMESTEPS",
    "DEFAULT_WARMUP_EPISODES",
    "ENV_CONFIG",
    "FITNESS_VERSION_DEFAULT",
    "GENERATION_MAX_RETRIES",
    "GENERATION_MAX_TOKENS",
    "GENERATION_TEMPERATURE",
    "KEY_ROTATION_MAX_ROUNDS",
    "KEY_ROTATION_WAIT_SEC",
    "LLM_MODEL",
    "LLM_PROVIDER",
    "LOG_FILE",
    "PPO_BATCH_SIZE",
    "PPO_N_EPOCHS",
    "PPO_N_STEPS",
    "REWARD_STEP_CLIP_MAX",
    "REWARD_STEP_CLIP_MIN",
    "REWARD_PROGRAM_PATH",
    "REWARD_STEP_TIMEOUT_SEC",
    "SANDBOX_EXECUTE_TIMEOUT_SEC",
    "SMOKE_TEST_TIMEOUT_SEC",
    "TRAJECTORY_BANK_MODE",
    "TRAJECTORY_BANK_SEED",
    "TRAJECTORY_REF_FITNESS_VERSION",
    "WEIGHTS_FILE",
    "API_KEYS_FILE",
]
